### ISSUE TITLE
1

### ISSUE THREAD

**Issue by oljindudol** [EliF-ASeN/shareKakao#2]
1.chat_id는 임의인가요?

2.대상의 user_id는 알아내나요

3. 복수멘션도 가능한가요?

**Comment by LiF-Lee** [comment]
1. 방 생성 할 때 정해지는 고유 방 아이디입니다.

2. DB 사용하시면 보실 수 있습니다.

3. 가능합니다.

**Comment by oljindudol** [comment]
빠답 감사드립니다

> 1. 방 생성 할 때 정해지는 고유 방 아이디입니다. 
   이것도 DB에서 보는건가요?
>2. DB 사용하시면 보실 수 있습니다. 
http://sharku.egloos.com/1321024
여기보면서 복호화하는법 따라해보고있는데
 1)같은방법론으로 가능한건가요?
 2)friend쪽보면 대는건가용?
 3)참고문서같은거 잇스실가용

**Comment by LiF-Lee** [comment]
1. 맞습니다.
2. 9.x 버전부터 암호화 방식이 달라져서 저 방법으로는 아마 못할겁니다. https://cafe.naver.com/nameyee/27185 복호화는 여기 참고하시면 될듯합니다.
