### ISSUE TITLE
메신저봇에서 shareKakao 모듈을 사용하려고 합니다.

### ISSUE THREAD

**Issue by maplespec** [EliF-ASeN/shareKakao#4]
TypeError: Cannot call method "split" of null (file:/storage/emulated/0/msgbot/global_modules/share.js#25)	at file:/storage/emulated/0/msgbot/global_modules/share.js:25
	at file:/storage/emulated/0/msgbot/global_modules/share.js:63

이렇게 
#25 :  t.reset(), t.update(this.j(this.k[3] + this.r(this.pa + this.p.pu).split(this.d)[1].split("</string>")[0]).getBytes());
#63 :  const response = org.jsoup.Jsoup.connect("https://talk-shareex.kakao.com/authWrite")

여기서 오류가 납니다...
25번째 줄에서 thid.d 내용으로 split 시키는데 KakaoTalk.hw.perferences.xml (this.pa + this.p.pu)에서 deviceUUID를 찾을 수 없었습니다. 카톡 버전에 의해 사용하지 못하는건가요 이제..?

**Comment by LiF-Lee** [comment]
9.* 이후 버전은 제가 현재 확인할 방법이 없기 때문에 사용할 수 없다고 확답을 드릴 순 없습니다만, DeviceUUid를 가져오는 폴더의 위치가 변경된것 같네요. 경로만 수정하면 작동할 듯 합니다.

**Comment by maplespec** [comment]
정상 작동하는 8.9.7로도 해봤으나 동일한 Error입니다.
deviceUUID는 8.9.7 버전에서는 정상적으로 보입니다만 
동일하게 this.r(this.pa + this.p.pu)이 null 값을 반환합니다.

t.prototype.r = function(t) {
        return FileStream.read(t);
}
를 보아 FileStream.read 함수를 못 불러오는 거 같은데 방법이 있을까요?

**Comment by maplespec** [comment]
8.9.7로 내렸습니다.
원인을 추적해보니 앱에서 data/data/com.kakao.talk/shared/prefs/~~ 에 접근을 못하여 null이 뜹니다.
휴대폰 루팅도 되어있는 상태인데 해결책이 없을까요?

**Comment by LiF-Lee** [comment]
버전 내리기 전에는 DB 접근이 가능했나요?

**Comment by maplespec** [comment]
버전 내리기 전에는 시도해보지 않았습니다만 adb로 파일 열람은 했었습니다

**Comment by maplespec** [comment]
해결했습니다!
다만 type을 2로하고 이미지 path를 웹 url로 지정했는데 나오지 않는것은 어떻게 해야할까요?

**Comment by LiF-Lee** [comment]
카카오 서버(ex. http://dn-m.talk.kakao.com/talkm/abcd/abcdefg/a.jpg)에 저장된 이미지 url을 입력해야합니다.

**Comment by LiF-Lee** [comment]
talkm/oYxiyx1A4b/UTAlvDGtDf8czGPx18bmak/i_bdaf681b1d0a.jpeg

path 부분에 넣고 실행해보시면 사진 나올거에요.

**Comment by maplespec** [comment]
안되네요... 인터넷에서 사이트 접속 시 잘 나오는데 카톡 메시지에선 아무 사진도 뜨지 않습니다

**Comment by LiF-Lee** [comment]
일반 텍스트는 잘 전송되나요? path 부분에는 talkm으로 시작해야 됩니다.

**Comment by maplespec** [comment]
넵 텍스트는 아주 잘 됩니다. shout도 전송은 되는데 그냥 일반 텍스트랑 똑같이 작동했고
"type": 2,
            "message": "사진",
            "attatchment": {
                "type": "image/jpeg",
                "w": 210,
                "h": 210,
                "path": "talkm/oYxiyx1A4b/UTAlvDGtDf8czGPx18bmak/i_bdaf681b1d0a.jpeg"
            }

이렇게했으나 나오지 않네요...

**Comment by LiF-Lee** [comment]
![F47A2CF6-A3E2-434C-9AB5-ED0091D46DE7](https://user-images.githubusercontent.com/66173558/130421475-461f9e26-a6f2-4e86-831b-37c45e2881ed.jpeg)

위 사진처럼 사진이 나오지 않는다는 건가요? 아니면 아무것도 전송된게 없다는 뜻인가요?

**Comment by maplespec** [comment]
![9DAA302B-1483-409F-A34A-C88758AC7F62](https://user-images.githubusercontent.com/56834573/130421973-75dec00c-6027-4b95-b940-5b337e76b21f.jpeg)

이렇게 나옵니다

**Comment by maplespec** [comment]
올려주신 내용과 상태가 동일합니다...
멘션도 작동하지 않네요

**Comment by LiF-Lee** [comment]
사진에 대해서는 뭐가 문젠지 잘 모르겠네요. 멘션은 userId를 정확하게 넣었고 문자열로 감싸주셨나요?

**Comment by maplespec** [comment]
넵 당연합니다...
결과는 @로만 나옵니다
사진은 템플릿은 맞게 나오나 사진없이 흰 화면만 나옵니다

**Comment by LiF-Lee** [comment]
멘션 쪽에 사용하신 코드 한번만 올려주세요.

**Comment by maplespec** [comment]
사진은 해결 법이 없을까요? ㅠ

**Comment by LiF-Lee** [comment]
사진 쪽엔 별 문제가 없어서.. 다른 기기에서 사진이 보이는지 확인해보세요.

**Comment by maplespec** [comment]
확인해봤는데 안됐습니다...
작동하는 코드 좀 공유해주실 수 있을까요?

**Comment by LiF-Lee** [comment]
`Kakao.share("28994573165447", { 
    "type": 1,
    "message": "@@",
    "attachment": {
        "mentions": [{
            "at": [1],
            "len": 0, 
            "user_id": "17383838474165785"
        }, 
       {
            "at": [2],
            "len": 0, 
            "user_id": "17383838474165785"
        }]
    }
});`

**Comment by maplespec** [comment]
앗 멘션 소스군요... 혹시 사진 소스는 가능할까요..?

**Comment by LiF-Lee** [comment]
예시로 올려둔 코드와 같습니다.

**Comment by maplespec** [comment]
![image](https://user-images.githubusercontent.com/56834573/131217388-e8931b6d-6458-482b-97fe-ce96cf8c64cc.png)
![image](https://user-images.githubusercontent.com/56834573/131217408-b10af7e1-5a16-40a5-84fe-1b12355333d0.png)
이렇게 되는데 ... 이미지 링크는 들어가보면 정상적으로 뜹니다. 예시 코드와 똑같이 했는데 막힌건가요? 카카오톡 버전은 Readme에 있는 버전과 동일합니다 (8.9.7)...

**Comment by ghost** [comment]
> 이렇게 되는데 ... 이미지 링크는 들어가보면 정상적으로 뜹니다. 예시 코드와 똑같이 했는데 막힌건가요? 카카오톡 버전은 Readme에 있는 버전과 동일합니다 (8.9.7)...

attachment입니다 attatchment가 아니에요
