### ISSUE TITLE
Share Simple Image가 작동하지 않습니다.

### ISSUE THREAD

**Issue by devitoolz** [EliF-ASeN/shareKakao#7]
path에 "talkm/~~.jpeg" 크롬으로 확인된 이미지 주소를 넣었으나
모바일에서 보니 0바이트 짜리 빈 이미지가 출력됩니다.
![KakaoTalk_20210828_210935844](https://user-images.githubusercontent.com/4100341/132092172-252e2d2b-cc07-49a8-b0ce-2c35941be42f.jpg)

**Comment by ghost** [comment]
이미지를 클릭했을때는 이미지가 정상적으로 표시되나요?

**Comment by ghost** [comment]
방금 확인결과, 미리보기가 정상적으로 표시됩니다.

**Comment by devitoolz** [comment]
아니요... 소스 문제는 없어보이는데 자꾸 말썽입니다...
도움 좀 요청드려도 될까요?

**Comment by ghost** [comment]
> 아니요... 소스 문제는 없어보이는데 자꾸 말썽입니다...
> 도움 좀 요청드려도 될까요?

해당 문제가 발생한 코드를 주실수 있으신가요?

**Comment by devitoolz** [comment]
앗 메봇카페 채팅드릴게요 !
